repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: trailing-whitespace
    - id: check-json
    - id: check-yaml
    - id: detect-aws-credentials
# Ansible linter
-   repo: https://github.com/ansible/ansible-lint
    rev: v5.0.7
    hooks:
    -   id: ansible-lint
        exclude: >
            (?x)^(
                .pre-commit-config.yaml
            )$
        files: \.(yaml|yml)$
